version: "3.9"
services:
  web:
    build:
      context: .
      network: host
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: index.py
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
