version: "3.8"
services:
  web:
    image: morra
    env_file:
      .env
    ports:
      - "5000:5000"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  mysql:
    env_file:
      .env
    image: "mysql"
