version: "3.9"
services:
  web:
    depends_on:
      - mysql
      - redis
    build:
      context: .
      network: host
    env_file:
      testing_vars.env
    entrypoint: [ "./wait-for", "mysql:3306", "--", "python", "-u", "index.py" ]
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mysql:
    env_file:
      testing_vars.env
    image: "mysql"
