version: "3.8"
services:
  web:
    build:
      context: .
      network: host
    env_file:
      .env
    ports:
      - 5000:5000
  redis:
    image: "redis"
  mysql:
    env_file:
      .env
    image: "mysql"
    volumes:
      - testvol:/var/lib/mysql

volumes:
  testvol:
