BCRYPT_SALT_ROUNDS = 10
JWT_TEST_KEY = "CiaO6CiAo55provA23HEY12321451"
WIN_AT = 12
QUEUE_STATUS_POLL_SECONDS = 6
ROUND_MOVE_WAIT_SECONDS = 10
MATCH_START_DELAY = ROUND_MOVE_WAIT_SECONDS+5
EXTRA_WAIT_SECONDS = 0  # rischia di fare più danni che bene forse quindi per ora 0
